const messages = {
    en: {
        message: {
            // main
            email_sent: "A verification email has been sent to your mailbox",
            email_failure: "Failed to send verification email",
            // datatypes
            unknown: "Unknown",
            accident: "Accident",
            incident: "Incident",
            airplane: "Airplane",
            helicopter: "Helicopter",
            experimental: "Experimental",
            drone: "Drone",
            // Home
            vision: "The general vision of the FlySafe project is to provide a technological and agile tool within the framework of the Da Vinci School system integration project; to the management of air safety and establish the guidelines for the process of continuous improvement of the same; Security goes beyond this project and opens a window to future self-managed systems.",
            safety_recommendations: "Safety recommendations",
            rso_description: "Safety recommendations are the main tool that the aeronautical system has to avoid future accidents",
            news: "News",
            personal_information: "Personal information",
            android_app: "Android App",
            features: "Features",
            documentation: "Documentation",
            // App
            admin: "Admin",
            user: "User",
            login: "Log in",
            logout: "Log out",
            home: "Home",
            reports: "Reports",
            search: "Search",
            stats: "Stats",
            options: "Options",
            // Reports
            my_reports: "My reports",
            new_report: "New Report",
            rep_not_validated: "Not validated",
            rep_invalid: "Invalid",
            rep_valid: "Valid",
            rep_solved: "Solved",
            // ReportsList
            date: "Date",
            type: "Type",
            aircraft_s: "Aircraft",
            narrative: "Narrative",
            // Aircraft
            registration: "Registration",
            // NewReport
            choose_an_option: "Choose an option",
            descrive_the_event: "Descrive the event...",
            add_aircraft: "Add Aircraft",
            photo: "Photo",
            new_aircraft: "New Aircraft",
            send_report: "Send Report",
            cancel: "Cancel",
            required: "Required",
            date_field_required: "The date field is required",
            occurrence_type_required: "Occurrence type is required",
            aircraft_required: "You have to add at least one aircraft",
            all_fields_required: "All fields are required",
            // ReportsSearch
            search_description: "Searches for event reports are associated with the registration of aircraft as it is the most relevant data in an event. The registration is the identification of the aircraft, so if an aircraft has more than one event through this form you can see all the events related to the aircraft.",
            search_v: "Search",
            searching: "Searching...",
            registration_required: "Aircraft registration is required",
            no_reports_found: "No reports found",
            // Stats
            stats_description: "When FlySafe receives a report of an event, a technical team is responsible for validating it, and ensuring the quality of the information, avoiding duplicate reports, false positives or false reports. That is why if a report is not validated or rejected, it may not meet the requirements of a report.",
            reports_map: "Reports map",
            reports_map_1: "The report map provides a general and georeferenced view of the events reported on the FlySafe platform.",
            reports_map_2: "The update is in real time and includes the last 100 reports even if they are not validated; So the information in the report map can be modified and / or updated periodically.",
            // BarChart
            total_reports: "Total Reports",
            not_validated: "Not Validated",
            rejected: "Rejected",
            accepted: "Accepted",
            // AndroidApp
            app_description_1: "FlySafe is available for devices with Android 4.4.2 KitKat system onwards, which allows a wide range of devices compatible with FlySafe.",
            app_description_2: "You can download the application safely and free and install it yourself on your devices.",
            download: "Download",
            // DatosPersonales
            personal_information_description: "FlySafe complies with the requirements of Law 25.326 regarding the protection of personal data, users can request at any time the personal information that the application collects, they can also request that the information be deleted.",
            information_request_form: "Information request form",
            pii_law: "Law on protection of personal data 25,326",
            delete_account_link: "You can delete your account by clicking {0}.",
            here: "here",
            delete_account_q: "Are you sure you want to delete your account?",
            account_deleted: "Your account has been deleted",
            account_deleted_error: "An error has occurred while deleting your account.",
            // Documentacion
            documentation_description: "All the documentation on FlySafe, the Project Plan, Use Cases, Gantt Letter, Source Code, etc. is available on Google Drive.",
            help_intro: "In this section you will find information of interest for the use of FlySafe; as well as all the technical documentation of the platform.",
            latest_version: "Latest version:",
            app_month: "December",
            web_month: "December",
            user_manual_h: "User manual",
            installation_manual_h: "Installation manual",
            faq1: "What can I report?",
            faq1a: "Accidents, aviation incidents of civil aircraft (aircraft, helicopters, gliders, drones, etc.)",
            faq2: "Does it have legal consequences?",
            faq2a: "No, the reports are only for the purpose of avoiding future events.",
            faq3: "Is FlySafe available for iOS?",
            faq3a: "No, it is currently available for Android and web browsers.",
            faq4: "My report was not validated. Why?",
            faq4a: "Reports are evaluated, if they do not fit into an aviation event, it will not be valid.",
            gdrive_access: "Access to the Documentation Drive",
            source_code: "Source Code",
            github_access: "GitHub Access",
            firebase_functions: "Firebase Functions",
            // Funcionalidades
            flysafe_info: "Information about FlySafe",
            apk_download: "APK Download",
            online_report_form: "Online reports form - registered users",
            latest_reports: "Latest events reported",
            exclusive_access: "Exclusive access for registered users",
            my_reports_status: "Status of your reports",
            user_manual: "User manual / current regulations",
            language_es_en: "Spanish / English language",
            user_registration: "User registration",
            online_report_form_2: "Report form for registered users",
            images_for_reports: "Images for reports",
            georeferencing: "Georeferencing",
            in_case_of_accident_1: "Information to act in the event of a plane crash (Aeronautical personnel)",
            in_case_of_accident_2: "Information to take into account before a plane crash (General Public)",
            // Options
            account_data: "Account data",
            help: "Help",
        }
    },
    es: {
        message: {
            // main
            email_sent: "Se ha enviado un email de verificación a su casilla de correo",
            email_failure: "No se ha podido enviar el email de verificación",
            // datatypes
            unknown: "Se desconoce",
            accident: "Accidente",
            incident: "Incidente",
            airplane: "Avión",
            helicopter: "Helicoptero",
            experimental: "Experimental",
            drone: "Dron",
            // Home
            vision: "La visión general del proyecto FlySafe, es la de aportar una herramienta tecnológica y ágil en el marco del proyecto de integración de sistemas de la Escuela Da Vinci; a la gestión de la seguridad operacional aérea y establecer los lineamientos para el proceso de mejora continua de la misma; la seguridad va más allá del presente proyecto y abre una ventana a futuros sistemas autogestionados.",
            safety_recommendations: "Recomendaciones sobre seguridad operacional",
            rso_description: "Las RSO son la principal herramienta que tiene el sistema aeronáutico para evitar futuros accidentes",
            news: "Novedades",
            personal_information: "Información personal",
            android_app: "App Android",
            features: "Funcionalidades",
            documentation: "Documentación",
            // App
            admin: "Admin",
            user: "Usuario",
            login: "Iniciar sesión",
            logout: "Cerrar sesión",
            home: "Inicio",
            reports: "Reportes",
            search: "Búsqueda",
            stats: "Estadísticas",
            options: "Opciones",
            // Reports
            my_reports: "Mis reportes",
            new_report: "Nuevo Reporte",
            rep_not_validated: "Sin validar",
            rep_invalid: "Inválido",
            rep_valid: "Válido",
            rep_solved: "Resuelto",
            // ReportsList
            date: "Fecha",
            type: "Tipo",
            aircraft_s: "Aeronaves",
            narrative: "Narrativa",
            // Aircraft
            registration: "Matrícula",
            // NewReport
            choose_an_option: "Elija una opción",
            descrive_the_event: "Describa el suceso...",
            add_aircraft: "Agregar Aeronave",
            photo: "Foto",
            new_aircraft: "Nueva Aeronave",
            send_report: "Enviar Reporte",
            cancel: "Cancelar",
            required: "Obligatorio",
            date_field_required: "El campo fecha es obligatorio",
            occurrence_type_required: "El tipo de suceso es obligatorio",
            aircraft_required: "Se tiene que agregar al menos una aeronave",
            all_fields_required: "Todos los campos son obligatorios",
            // ReportsSearch
            search_description: "Las búsquedas de reportes de sucesos, están asociadas a la matrícula de las aeronaves ya que es el dato mas relevante en un suceso. La matrícula es la identificacion de la aeronave, por lo que si una aeronave tiene mas de un suceso mediante este formulario se podran ver todos los eventos relacionados con la aeronave.",
            search_v: "Buscar",
            searching: "Buscando...",
            registration_required: "Se debe especificar la matrícula",
            no_reports_found: "No se han encontrado reportes",
            // Stats
            stats_description: "FlySafe cuando recibe un reporte de un suceso, un equipo técnico se encarga de validarlo, y asegurar la calidad de la información, evitando reportes duplicados, falsos positivos o reportes falsos. Es por ello que si un reporte no está validado o es rechazado, puede ser que no cumpla con los requisitos de un reporte.",
            reports_map: "Mapa de reportes",
            reports_map_1: "El mapa de reportes brinda una vista general y georreferenciada de los sucesos reportados en la plataforma FlySafe.",
            reports_map_2: "La actualización es en tiempo real e incluye los últimos 100 reportes aún cuando no estén validados; por lo que la información del mapa de reportes puede ser modificada y/o actualizada periódicamente.",
            // BarChart
            total_reports: "Reportes Totales",
            not_validated: "No Validados",
            rejected: "Rechazados",
            accepted: "Aceptados",
            // AndroidApp
            app_description_1: "FlySafe se encuentra disponible para dispositivos con sistema Android 4.4.2 KitKat en adelante, lo que permite una amplia gama de dispositivos compatibles con FlySafe.",
            app_description_2: "Podes descargar la aplicación de manera segura y gratuita e instalarla tu mismo en tus dispositivos.",
            download: "Descargar",
            // DatosPersonales
            personal_information_description: "FlySafe cumple con los requerimientos de la Ley 25.326 en cuanto a la protección de datos personales, los usuarios pueden solicitar en cualquier momento la información personal que recopila la aplicación, asimismo puede solicitar que la información sea eliminada.",
            information_request_form: "Formulario de solicitud de información",
            pii_law: "Ley de protección de datos personales 25.326",
            delete_account_link: "Puede eliminar su cuenta haciendo click {0}.",
            here: "aquí",
            delete_account_q: "¿Está seguro que quiere eliminar su cuenta de usuario?",
            account_deleted: "Su cuenta ha sido eliminada",
            account_deleted_error: "Ha ocurrido un error al borrar su cuenta.",
            // Documentacion
            documentation_description: "Toda la documentación sobre FlySafe, el Plan de Proyecto, Casos de Uso, Carta Gantt, Código Fuente, etc. está disponible en Google Drive.",
            help_intro: "En esta sección usted encontrará información de interés para el uso de FlySafe; como así también toda la documentación técnica de la plataforma.",
            latest_version: "Última versión:",
            app_month: "diciembre",
            web_month: "diciembre",
            user_manual_h: "Manual de usuario",
            installation_manual_h: "Manual de instalación",
            faq1: "¿Qué puedo reportar?",
            faq1a: "Accidentes, incidentes de aviación de aeronaves civiles (avión, helicópteros, planeadores, drones, etc)",
            faq2: "¿Tiene consecuencias legales?",
            faq2a: "No, los reportes son sólo a fines de evitar futuros eventos.",
            faq3: "¿FlySafe está disponible para iOS?",
            faq3a: "No, por el momento está disponible para Android y navegadores web.",
            faq4: "Mi reporte no fue validado. ¿Por qué?",
            faq4a: "Los reportes son evaluados, si no encuadran en un suceso de aviación, no será válido.",
            gdrive_access: "Acceso al Drive de Documentación",
            source_code: "Código Fuente",
            github_access: "Acceso a GitHub",
            firebase_functions: "Funciones de Firebase",
            // Funcionalidades
            flysafe_info: "Información sobre FlySafe",
            apk_download: "Descarga de APK",
            online_report_form: "Formulario de denuncia online - usuarios registrados",
            latest_reports: "Últimos reportes denunciados",
            exclusive_access: "Acceso exclusivo para usuarios registrados",
            my_reports_status: "Estado actual de mis reportes",
            user_manual: "Manual de usuario / reglamentación vigente",
            language_es_en: "Idioma Español / inglés",
            user_registration: "Registro de usuarios",
            online_report_form_2: "Formulario de reportes para usuarios registrados",
            images_for_reports: "Imágenes para reportes",
            georeferencing: "Georeferenciación",
            in_case_of_accident_1: "Información para actuar en caso de accidente aéreo (Personal aeronáutico)",
            in_case_of_accident_2: "Información para tener en cuenta ante un accidente aéreo (Público en Gral.)",
            // Options
            account_data: "Datos de la cuenta",
            help: "Ayuda",
        }
    }
}

export default messages;
